# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WakeMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WakeMe
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/RemoteConfig'

  target 'WakeMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WakeMe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WakeMe-tvOS

  target 'WakeMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
